const Actions = {
  GET_INGREDIENTS: 'ingredients/GET_INGREDIENTS',
  GET_INGREDIENTS_SUCCESS: 'ingredients/GET_INGREDIENTS_SUCCESS',
  GET_INGREDIENTS_FAILURE: 'ingredients/GET_INGREDIENTS_FAILURE',

  DRAG_INGREDIENT: 'ingredients/DRAG_INGREDIENT',
  DROP_INGREDIENT: 'ingredients/DROP_INGREDIENT',

  ADD_INGREDIENT_TO_CONSTRUCTOR: 'constructor-ingredients/ADD_INGREDIENT_TO_CONSTRUCTOR',
  REMOVE_INGREDIENT_FROM_CONSTRUCTOR: 'constructor-ingredients/REMOVE_INGREDIENT_FROM_CONSTRUCTOR',
  RESET_CONSTRUCTOR_INGREDIENTS: 'constructor-ingredients/RESET_CONSTRUCTOR_INGREDIENTS',
  ADD_BUN_TO_CONSTRUCTOR: 'constructor-ingredients/ADD_BUN_TO_CONSTRUCTOR',
  CHANGE_CONSTRUCTOR_INGREDIENT_POSITION: 'constructor-ingredients/CHANGE_CONSTRUCTOR_INGREDIENT_POSITION',

  SET_DETAILED_INGREDIENT: 'detailed-ingredient/SET_DETAILED_INGREDIENT',
  RESET_DETAILED_INGREDIENT: 'detailed-ingredient/RESET_DETAILED_INGREDIENT',

  POST_ORDER: 'order/POST_ORDER',
  POST_ORDER_SUCCESS: 'order/POST_ORDER_SUCCESS',
  POST_ORDER_FAILURE: 'order/POST_ORDER_FAILURE',
  RESET_ORDER_NUMBER: 'order/RESET_ORDER_NUMBER',
};

export default Actions;
