const Actions = {
  GET_INGREDIENTS: 'ingredients/GET_INGREDIENTS',
  GET_INGREDIENTS_SUCCESS: 'ingredients/GET_INGREDIENTS_SUCCESS',
  GET_INGREDIENTS_FAILURE: 'ingredients/GET_INGREDIENTS_FAILURE',

  ADD_INGREDIENT: 'constructor-ingredients/ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'constructor-ingredients/REMOVE_INGREDIENT',
  RESET_INGREDIENTS: 'constructor-ingredients/RESET_INGREDIENTS',

  SET_DETAILED_INGREDIENT: 'detailed-ingredient/SET_DETAILED_INGREDIENT',
  RESET_DETAILED_INGREDIENT: 'detailed-ingredient/RESET_DETAILED_INGREDIENT',

  POST_ORDER: 'order/POST_ORDER',
  POST_ORDER_SUCCESS: 'order/POST_ORDER_SUCCESS',
  POST_ORDER_FAILURE: 'order/POST_ORDER_FAILURE',
};

export default Actions;
