export const ADD_INGREDIENT_TO_CONSTRUCTOR: 'constructor-ingredients/ADD_INGREDIENT_TO_CONSTRUCTOR' = 'constructor-ingredients/ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR: 'constructor-ingredients/REMOVE_INGREDIENT_FROM_CONSTRUCTOR' = 'constructor-ingredients/REMOVE_INGREDIENT_FROM_CONSTRUCTOR';
export const RESET_CONSTRUCTOR_INGREDIENTS: 'constructor-ingredients/RESET_CONSTRUCTOR_INGREDIENTS' = 'constructor-ingredients/RESET_CONSTRUCTOR_INGREDIENTS';
export const ADD_BUN_TO_CONSTRUCTOR: 'constructor-ingredients/ADD_BUN_TO_CONSTRUCTOR' = 'constructor-ingredients/ADD_BUN_TO_CONSTRUCTOR';
export const CHANGE_CONSTRUCTOR_INGREDIENT_POSITION: 'constructor-ingredients/CHANGE_CONSTRUCTOR_INGREDIENT_POSITION' = 'constructor-ingredients/CHANGE_CONSTRUCTOR_INGREDIENT_POSITION';
